build as dkms
intel/ivsc-driver pull request #13
Opened 2022-05-04 10:59 UTC by vicamo

Header files in `backport-include` was copied from each kernel release and merged. For those who would like to copy the source files into kernel tree and compile inlinely, it can be skipped. Debianization is mostly ready in https://code.launchpad.net/~vicamo/+git/intel-vsc-dkms/+ref/ubuntu/devel .

2022-05-04 11:05 UTC, vicamo commented on drivers/misc/mei/Makefile
> +ccflags-y += -I$(src)/../../../backport-include/drivers/misc/mei
It should be nice to add a comment above this line saying it should be skipped when compiled in tree.

2022-05-05 00:27 UTC, wentongwu commented
the added Makefile in sub folder(like gpio, i2c, etc) will block other real hardware building on ADL if vendors still choose in-tree building. Please delete these Makefiles except the root one. And add the objs and including in the root Makefile. Thanks

2022-05-05 00:27 UTC, wentongwu commented
the added Makefile in sub folder(like gpio, i2c, etc) will block other real hardware building on ADL if vendors still choose in-tree building. Please delete these Makefiles except the root one. And add the objs and including in the root Makefile. Thanks

2022-05-05 00:30 UTC, wentongwu requested changes
the added Makefile in sub folder(like gpio, i2c, etc) will block other real hardware building on ADL if vendors still choose in-tree building. Please delete these Makefiles except the root one. And add the objs and including in the root Makefile. Thanks

2022-05-06 08:43 UTC, closed without merging

2022-05-06 09:03 UTC, wentongwu commented
@vicamo why you close this PR? it just need a little change to merge it.